name: Build
on: [ push ]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Gradle Version
        uses: gradle/gradle-build-action@v2
        with:
          arguments: --version
      - name: Gradle Assemble
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble
      - name: Gradle Check
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check
